/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as CommitteeRouteImport } from './routes/committee'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as RoutineRouteImport } from './routes/routine'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as TtProdhanRouteImport } from './routes/tt-prodhan'
import { Route as NoticesIndexRouteImport } from './routes/notices.index'
import { Route as NoticesSlugRouteImport } from './routes/notices.$slug'
import { Route as TtProdhanIndexRouteImport } from './routes/tt-prodhan.index'
import { Route as TtProdhanSectionRouteImport } from './routes/tt-prodhan.$section'
import { Route as TtProdhanGuideRouteImport } from './routes/tt-prodhan.guide'
import { Route as TtProdhanMediaRouteImport } from './routes/tt-prodhan.media'
import { Route as TtProdhanPasswordRouteImport } from './routes/tt-prodhan.password'
import { Route as TtProdhanSettingsRouteImport } from './routes/tt-prodhan.settings'
import { Route as TtProdhanUsersRouteImport } from './routes/tt-prodhan.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteeRoute = CommitteeRouteImport.update({
  id: '/committee',
  path: '/committee',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutineRoute = RoutineRouteImport.update({
  id: '/routine',
  path: '/routine',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const TtProdhanRoute = TtProdhanRouteImport.update({
  id: '/tt-prodhan',
  path: '/tt-prodhan',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesIndexRoute = NoticesIndexRouteImport.update({
  id: '/notices/',
  path: '/notices/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesSlugRoute = NoticesSlugRouteImport.update({
  id: '/notices/$slug',
  path: '/notices/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TtProdhanIndexRoute = TtProdhanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TtProdhanRoute,
} as any)
const TtProdhanSectionRoute = TtProdhanSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => TtProdhanRoute,
} as any)
const TtProdhanGuideRoute = TtProdhanGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => TtProdhanRoute,
} as any)
const TtProdhanMediaRoute = TtProdhanMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => TtProdhanRoute,
} as any)
const TtProdhanPasswordRoute = TtProdhanPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => TtProdhanRoute,
} as any)
const TtProdhanSettingsRoute = TtProdhanSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TtProdhanRoute,
} as any)
const TtProdhanUsersRoute = TtProdhanUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => TtProdhanRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admin-login': typeof AdminLoginRoute
  '/committee': typeof CommitteeRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/routine': typeof RoutineRoute
  '/teachers': typeof TeachersRoute
  '/tt-prodhan': typeof TtProdhanRouteWithChildren
  '/notices/$slug': typeof NoticesSlugRoute
  '/tt-prodhan/$section': typeof TtProdhanSectionRoute
  '/tt-prodhan/guide': typeof TtProdhanGuideRoute
  '/tt-prodhan/media': typeof TtProdhanMediaRoute
  '/tt-prodhan/password': typeof TtProdhanPasswordRoute
  '/tt-prodhan/settings': typeof TtProdhanSettingsRoute
  '/tt-prodhan/users': typeof TtProdhanUsersRoute
  '/notices/': typeof NoticesIndexRoute
  '/tt-prodhan/': typeof TtProdhanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admin-login': typeof AdminLoginRoute
  '/committee': typeof CommitteeRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/routine': typeof RoutineRoute
  '/teachers': typeof TeachersRoute
  '/notices/$slug': typeof NoticesSlugRoute
  '/tt-prodhan/$section': typeof TtProdhanSectionRoute
  '/tt-prodhan/guide': typeof TtProdhanGuideRoute
  '/tt-prodhan/media': typeof TtProdhanMediaRoute
  '/tt-prodhan/password': typeof TtProdhanPasswordRoute
  '/tt-prodhan/settings': typeof TtProdhanSettingsRoute
  '/tt-prodhan/users': typeof TtProdhanUsersRoute
  '/notices': typeof NoticesIndexRoute
  '/tt-prodhan': typeof TtProdhanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admin-login': typeof AdminLoginRoute
  '/committee': typeof CommitteeRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/routine': typeof RoutineRoute
  '/teachers': typeof TeachersRoute
  '/tt-prodhan': typeof TtProdhanRouteWithChildren
  '/notices/$slug': typeof NoticesSlugRoute
  '/tt-prodhan/$section': typeof TtProdhanSectionRoute
  '/tt-prodhan/guide': typeof TtProdhanGuideRoute
  '/tt-prodhan/media': typeof TtProdhanMediaRoute
  '/tt-prodhan/password': typeof TtProdhanPasswordRoute
  '/tt-prodhan/settings': typeof TtProdhanSettingsRoute
  '/tt-prodhan/users': typeof TtProdhanUsersRoute
  '/notices/': typeof NoticesIndexRoute
  '/tt-prodhan/': typeof TtProdhanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academics'
    | '/admin-login'
    | '/committee'
    | '/contact'
    | '/gallery'
    | '/routine'
    | '/teachers'
    | '/tt-prodhan'
    | '/notices/$slug'
    | '/tt-prodhan/$section'
    | '/tt-prodhan/guide'
    | '/tt-prodhan/media'
    | '/tt-prodhan/password'
    | '/tt-prodhan/settings'
    | '/tt-prodhan/users'
    | '/notices/'
    | '/tt-prodhan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academics'
    | '/admin-login'
    | '/committee'
    | '/contact'
    | '/gallery'
    | '/routine'
    | '/teachers'
    | '/notices/$slug'
    | '/tt-prodhan/$section'
    | '/tt-prodhan/guide'
    | '/tt-prodhan/media'
    | '/tt-prodhan/password'
    | '/tt-prodhan/settings'
    | '/tt-prodhan/users'
    | '/notices'
    | '/tt-prodhan'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academics'
    | '/admin-login'
    | '/committee'
    | '/contact'
    | '/gallery'
    | '/routine'
    | '/teachers'
    | '/tt-prodhan'
    | '/notices/$slug'
    | '/tt-prodhan/$section'
    | '/tt-prodhan/guide'
    | '/tt-prodhan/media'
    | '/tt-prodhan/password'
    | '/tt-prodhan/settings'
    | '/tt-prodhan/users'
    | '/notices/'
    | '/tt-prodhan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicsRoute: typeof AcademicsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  CommitteeRoute: typeof CommitteeRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  RoutineRoute: typeof RoutineRoute
  TeachersRoute: typeof TeachersRoute
  TtProdhanRoute: typeof TtProdhanRouteWithChildren
  NoticesSlugRoute: typeof NoticesSlugRoute
  NoticesIndexRoute: typeof NoticesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committee': {
      id: '/committee'
      path: '/committee'
      fullPath: '/committee'
      preLoaderRoute: typeof CommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routine': {
      id: '/routine'
      path: '/routine'
      fullPath: '/routine'
      preLoaderRoute: typeof RoutineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tt-prodhan': {
      id: '/tt-prodhan'
      path: '/tt-prodhan'
      fullPath: '/tt-prodhan'
      preLoaderRoute: typeof TtProdhanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices/': {
      id: '/notices/'
      path: '/notices'
      fullPath: '/notices/'
      preLoaderRoute: typeof NoticesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices/$slug': {
      id: '/notices/$slug'
      path: '/notices/$slug'
      fullPath: '/notices/$slug'
      preLoaderRoute: typeof NoticesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tt-prodhan/': {
      id: '/tt-prodhan/'
      path: '/'
      fullPath: '/tt-prodhan/'
      preLoaderRoute: typeof TtProdhanIndexRouteImport
      parentRoute: typeof TtProdhanRoute
    }
    '/tt-prodhan/$section': {
      id: '/tt-prodhan/$section'
      path: '/$section'
      fullPath: '/tt-prodhan/$section'
      preLoaderRoute: typeof TtProdhanSectionRouteImport
      parentRoute: typeof TtProdhanRoute
    }
    '/tt-prodhan/guide': {
      id: '/tt-prodhan/guide'
      path: '/guide'
      fullPath: '/tt-prodhan/guide'
      preLoaderRoute: typeof TtProdhanGuideRouteImport
      parentRoute: typeof TtProdhanRoute
    }
    '/tt-prodhan/media': {
      id: '/tt-prodhan/media'
      path: '/media'
      fullPath: '/tt-prodhan/media'
      preLoaderRoute: typeof TtProdhanMediaRouteImport
      parentRoute: typeof TtProdhanRoute
    }
    '/tt-prodhan/password': {
      id: '/tt-prodhan/password'
      path: '/password'
      fullPath: '/tt-prodhan/password'
      preLoaderRoute: typeof TtProdhanPasswordRouteImport
      parentRoute: typeof TtProdhanRoute
    }
    '/tt-prodhan/settings': {
      id: '/tt-prodhan/settings'
      path: '/settings'
      fullPath: '/tt-prodhan/settings'
      preLoaderRoute: typeof TtProdhanSettingsRouteImport
      parentRoute: typeof TtProdhanRoute
    }
    '/tt-prodhan/users': {
      id: '/tt-prodhan/users'
      path: '/users'
      fullPath: '/tt-prodhan/users'
      preLoaderRoute: typeof TtProdhanUsersRouteImport
      parentRoute: typeof TtProdhanRoute
    }
  }
}

interface TtProdhanRouteChildren {
  TtProdhanSectionRoute: typeof TtProdhanSectionRoute
  TtProdhanGuideRoute: typeof TtProdhanGuideRoute
  TtProdhanMediaRoute: typeof TtProdhanMediaRoute
  TtProdhanPasswordRoute: typeof TtProdhanPasswordRoute
  TtProdhanSettingsRoute: typeof TtProdhanSettingsRoute
  TtProdhanUsersRoute: typeof TtProdhanUsersRoute
  TtProdhanIndexRoute: typeof TtProdhanIndexRoute
}

const TtProdhanRouteChildren: TtProdhanRouteChildren = {
  TtProdhanSectionRoute: TtProdhanSectionRoute,
  TtProdhanGuideRoute: TtProdhanGuideRoute,
  TtProdhanMediaRoute: TtProdhanMediaRoute,
  TtProdhanPasswordRoute: TtProdhanPasswordRoute,
  TtProdhanSettingsRoute: TtProdhanSettingsRoute,
  TtProdhanUsersRoute: TtProdhanUsersRoute,
  TtProdhanIndexRoute: TtProdhanIndexRoute,
}

const TtProdhanRouteWithChildren = TtProdhanRoute._addFileChildren(
  TtProdhanRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicsRoute: AcademicsRoute,
  AdminLoginRoute: AdminLoginRoute,
  CommitteeRoute: CommitteeRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  RoutineRoute: RoutineRoute,
  TeachersRoute: TeachersRoute,
  TtProdhanRoute: TtProdhanRouteWithChildren,
  NoticesSlugRoute: NoticesSlugRoute,
  NoticesIndexRoute: NoticesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
